/*
 * Timmi Timesheet API
 * Welcome on the documentation for the Timmi Timesheet API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AxisSection
 */
public class AxisSectionTest {
    private final AxisSection model = new AxisSection();

    /**
     * Model tests for AxisSection
     */
    @Test
    public void testAxisSection() {
        // TODO: test AxisSection
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'multilingualName'
     */
    @Test
    public void multilingualNameTest() {
        // TODO: test multilingualName
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'startOn'
     */
    @Test
    public void startOnTest() {
        // TODO: test startOn
    }

    /**
     * Test the property 'endOn'
     */
    @Test
    public void endOnTest() {
        // TODO: test endOn
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'axisId'
     */
    @Test
    public void axisIdTest() {
        // TODO: test axisId
    }

    /**
     * Test the property 'parentAxisSections'
     */
    @Test
    public void parentAxisSectionsTest() {
        // TODO: test parentAxisSections
    }

    /**
     * Test the property 'childrenAxisSections'
     */
    @Test
    public void childrenAxisSectionsTest() {
        // TODO: test childrenAxisSections
    }

}
