/*
 * Timmi Timesheet API
 * Welcome on the documentation for the Timmi Timesheet API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TimeEntriesDeleteMultipleRequestInner
 */
public class TimeEntriesDeleteMultipleRequestInnerTest {
    private final TimeEntriesDeleteMultipleRequestInner model = new TimeEntriesDeleteMultipleRequestInner();

    /**
     * Model tests for TimeEntriesDeleteMultipleRequestInner
     */
    @Test
    public void testTimeEntriesDeleteMultipleRequestInner() {
        // TODO: test TimeEntriesDeleteMultipleRequestInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
