/*
 * Timmi Timesheet API
 * Welcome on the documentation for the Timmi Timesheet API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkflowSendReminderEmailResponseItemsInner
 */
public class WorkflowSendReminderEmailResponseItemsInnerTest {
    private final WorkflowSendReminderEmailResponseItemsInner model = new WorkflowSendReminderEmailResponseItemsInner();

    /**
     * Model tests for WorkflowSendReminderEmailResponseItemsInner
     */
    @Test
    public void testWorkflowSendReminderEmailResponseItemsInner() {
        // TODO: test WorkflowSendReminderEmailResponseItemsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'exceptionMessage'
     */
    @Test
    public void exceptionMessageTest() {
        // TODO: test exceptionMessage
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
