/*
 * Timmi Timesheet API
 * Welcome on the documentation for the Timmi Timesheet API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Transfer;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkflowSubmitTimesheetRequestTimesheetsInner
 */
public class WorkflowSubmitTimesheetRequestTimesheetsInnerTest {
    private final WorkflowSubmitTimesheetRequestTimesheetsInner model = new WorkflowSubmitTimesheetRequestTimesheetsInner();

    /**
     * Model tests for WorkflowSubmitTimesheetRequestTimesheetsInner
     */
    @Test
    public void testWorkflowSubmitTimesheetRequestTimesheetsInner() {
        // TODO: test WorkflowSubmitTimesheetRequestTimesheetsInner
    }

    /**
     * Test the property 'startsAt'
     */
    @Test
    public void startsAtTest() {
        // TODO: test startsAt
    }

    /**
     * Test the property 'endsAt'
     */
    @Test
    public void endsAtTest() {
        // TODO: test endsAt
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'transfers'
     */
    @Test
    public void transfersTest() {
        // TODO: test transfers
    }

}
