/*
 * Timmi Timesheet API
 * Welcome on the documentation for the Timmi Timesheet API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WorkflowCancelTimesheetByIdRequestTimesheetsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkflowCancelTimesheetByIdRequest
 */
public class WorkflowCancelTimesheetByIdRequestTest {
    private final WorkflowCancelTimesheetByIdRequest model = new WorkflowCancelTimesheetByIdRequest();

    /**
     * Model tests for WorkflowCancelTimesheetByIdRequest
     */
    @Test
    public void testWorkflowCancelTimesheetByIdRequest() {
        // TODO: test WorkflowCancelTimesheetByIdRequest
    }

    /**
     * Test the property 'timesheets'
     */
    @Test
    public void timesheetsTest() {
        // TODO: test timesheets
    }

}
