/*
 * Timmi Timesheet API
 * Welcome on the documentation for the Timmi Timesheet API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * WorkflowSendReminderEmailRequestTimesheetsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class WorkflowSendReminderEmailRequestTimesheetsInner {
  public static final String SERIALIZED_NAME_STARTS_AT = "startsAt";
  @SerializedName(SERIALIZED_NAME_STARTS_AT)
  private LocalDate startsAt;

  public static final String SERIALIZED_NAME_ENDS_AT = "endsAt";
  @SerializedName(SERIALIZED_NAME_ENDS_AT)
  private LocalDate endsAt;

  public static final String SERIALIZED_NAME_OWNER_ID = "ownerId";
  @SerializedName(SERIALIZED_NAME_OWNER_ID)
  private Integer ownerId;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public WorkflowSendReminderEmailRequestTimesheetsInner() {
  }

  public WorkflowSendReminderEmailRequestTimesheetsInner startsAt(LocalDate startsAt) {
    
    
    
    
    this.startsAt = startsAt;
    return this;
  }

   /**
   * Get startsAt
   * @return startsAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public LocalDate getStartsAt() {
    return startsAt;
  }


  public void setStartsAt(LocalDate startsAt) {
    
    
    
    this.startsAt = startsAt;
  }


  public WorkflowSendReminderEmailRequestTimesheetsInner endsAt(LocalDate endsAt) {
    
    
    
    
    this.endsAt = endsAt;
    return this;
  }

   /**
   * Get endsAt
   * @return endsAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public LocalDate getEndsAt() {
    return endsAt;
  }


  public void setEndsAt(LocalDate endsAt) {
    
    
    
    this.endsAt = endsAt;
  }


  public WorkflowSendReminderEmailRequestTimesheetsInner ownerId(Integer ownerId) {
    if (ownerId != null && ownerId < 1) {
      throw new IllegalArgumentException("Invalid value for ownerId. Must be greater than or equal to 1.");
    }
    
    
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * minimum: 1
   * @return ownerId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(Integer ownerId) {
    if (ownerId != null && ownerId < 1) {
      throw new IllegalArgumentException("Invalid value for ownerId. Must be greater than or equal to 1.");
    }
    
    
    this.ownerId = ownerId;
  }


  public WorkflowSendReminderEmailRequestTimesheetsInner comment(String comment) {
    
    
    
    
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    
    
    
    this.comment = comment;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WorkflowSendReminderEmailRequestTimesheetsInner instance itself
   */
  public WorkflowSendReminderEmailRequestTimesheetsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowSendReminderEmailRequestTimesheetsInner workflowSendReminderEmailRequestTimesheetsInner = (WorkflowSendReminderEmailRequestTimesheetsInner) o;
    return Objects.equals(this.startsAt, workflowSendReminderEmailRequestTimesheetsInner.startsAt) &&
        Objects.equals(this.endsAt, workflowSendReminderEmailRequestTimesheetsInner.endsAt) &&
        Objects.equals(this.ownerId, workflowSendReminderEmailRequestTimesheetsInner.ownerId) &&
        Objects.equals(this.comment, workflowSendReminderEmailRequestTimesheetsInner.comment)&&
        Objects.equals(this.additionalProperties, workflowSendReminderEmailRequestTimesheetsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startsAt, endsAt, ownerId, comment, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowSendReminderEmailRequestTimesheetsInner {\n");
    sb.append("    startsAt: ").append(toIndentedString(startsAt)).append("\n");
    sb.append("    endsAt: ").append(toIndentedString(endsAt)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("startsAt");
    openapiFields.add("endsAt");
    openapiFields.add("ownerId");
    openapiFields.add("comment");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("startsAt");
    openapiRequiredFields.add("endsAt");
    openapiRequiredFields.add("ownerId");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to WorkflowSendReminderEmailRequestTimesheetsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!WorkflowSendReminderEmailRequestTimesheetsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WorkflowSendReminderEmailRequestTimesheetsInner is not found in the empty JSON string", WorkflowSendReminderEmailRequestTimesheetsInner.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WorkflowSendReminderEmailRequestTimesheetsInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WorkflowSendReminderEmailRequestTimesheetsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WorkflowSendReminderEmailRequestTimesheetsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WorkflowSendReminderEmailRequestTimesheetsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WorkflowSendReminderEmailRequestTimesheetsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<WorkflowSendReminderEmailRequestTimesheetsInner>() {
           @Override
           public void write(JsonWriter out, WorkflowSendReminderEmailRequestTimesheetsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WorkflowSendReminderEmailRequestTimesheetsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             WorkflowSendReminderEmailRequestTimesheetsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WorkflowSendReminderEmailRequestTimesheetsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WorkflowSendReminderEmailRequestTimesheetsInner
  * @throws IOException if the JSON string is invalid with respect to WorkflowSendReminderEmailRequestTimesheetsInner
  */
  public static WorkflowSendReminderEmailRequestTimesheetsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WorkflowSendReminderEmailRequestTimesheetsInner.class);
  }

 /**
  * Convert an instance of WorkflowSendReminderEmailRequestTimesheetsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

